[env:esp32s3box]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200

; Configure memory architecture for ESP32-S3-WROOM-N16R8
; R8 indicates 8MB Octal SPI PSRAM. The compiler memory type must be explicitly set to qio_opi.

board_build.arduino.memory_type = qio_opi
board_build.flash_mode = qio
board_upload.flash_size = 16MB
; Enable PSRAM support to allocate large camera frame buffers safely.
build_flags = 
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue

; 自動下載原廠相機相容驅動程式庫
lib_deps =
    esp32-camera
    https://github.com/witnessmenow/Universal-Arduino-Telegram-Bot.git
    bblanchon/ArduinoJson@^6.21.0
